# Generated by Django 5.0.1 on 2024-01-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='name',
            field=models.CharField(default='Emilio', max_length=15),
            preserve_default=False,
        ),
    ]
